name: country_picker
description: new flutter project for copertino country picker

publish_to: none #prevent publishing of example app 

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_countries2:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
