name: flutter_countries2
description: 'A lite dart package for providing offline World Countries Data with helpful utils to your dart or flutter application'
  
version: 1.0.2

HomeScreen: https://github.com/barq-al-layl/countries_utils.git

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:


dev_dependencies: 
  lints: ^5.1.1 
  test: ^1.17.12

