name: countries_utils
description: 'A lite dart package for providing offline World Countires Data with helpful utils to your dart or flutter application'
  
version: 1.0.1

HomeScreen: https://github.com/egyleader/countries_utils.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:


dev_dependencies: 
  lints: ^1.0.1 
  test: ^1.17.12

